[package]
edition = "2021"
name    = "minipack"
version = "0.1.0"

[dependencies]
anyhow            = { workspace = true }
arcstr            = { workspace = true }
minipack_common   = { workspace = true }
minipack_fs       = { workspace = true, features = ["os"] }
minipack_resolver = { workspace = true }
rustc-hash        = { workspace = true }
sugar_path        = { workspace = true }
tokio             = { workspace = true, features = ["rt", "macros", "sync"] }

[dev-dependencies]
sugar_path = { workspace = true }
tokio      = { workspace = true, features = ["rt", "macros", "sync", "rt-multi-thread"] }
